[workspace]
members = ["rs-client", "rs-net", "rs-protocol", "rs-render", "rs-ui", "rs-utils"]
resolver = "3"
default-run = "rs-client"

[workspace.dependencies]
tracing = { version = "0.1.41" }
tracing-subscriber = "0.3.20"


